media.type.*.third_party.media_expire:
  type: mapping
  label: 'Expire settings'
  mapping:
    expire_field:
      type: string
      label: 'Datetime filed with expire information'
    enable_expiring:
      type: integer
      label: 'Indicates if expiring is enabled'
    fallback_media:
      type: string
      label: 'Fallback media'
