name: 'Configuration Selector'
type: module
description: 'A utility module that enables different versions of optional configuration to be selected on module install.'
core_version_requirement: ^10.2 || ^11
container_rebuild_required: true
