name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, hash, json, mbstring, pcre, pdo, session, tokenizer, zip
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
      
    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Put site in maintenance mode
          ./vendor/bin/drush state:set system.maintenance_mode 1 --input-format=integer
          
          # Pull latest code
          git pull origin main
          
          # Install/update dependencies
          composer install --no-dev --optimize-autoloader
          
          # Run database updates
          ./vendor/bin/drush updatedb -y
          
          # Import configuration
          ./vendor/bin/drush config:import -y
          
          # Clear caches
          ./vendor/bin/drush cache:rebuild
          
          # Disable maintenance mode
          ./vendor/bin/drush state:set system.maintenance_mode 0 --input-format=integer
          
          # Final cache clear
          ./vendor/bin/drush cache:rebuild
          
          echo "Deployment completed successfully!"